apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-api
  namespace: product-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
        - name: product-catalog
          image: product-catalog:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080