apiVersion: v1
kind: Service
metadata:
  name: product-catalog-api
  namespace: product-catalog
spec:
  selector:
    app: product-catalog
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080